## Append samples you want in your CSV to this file as resources ##
resources:
- appstudio_v1alpha1_releasestrategy.yaml
- appstudio_v1alpha1_release.yaml
- appstudio_v1alpha1_releaseplan.yaml
- appstudio_v1alpha1_releaseplanadmission.yaml
- appstudio_v1alpha1_releaseserviceconfig.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
