# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/appstudio.redhat.com_releases.yaml
- bases/appstudio.redhat.com_releaseplanadmissions.yaml
- bases/appstudio.redhat.com_releaseplans.yaml
- bases/appstudio.redhat.com_releasestrategies.yaml
- bases/appstudio.redhat.com_releaseserviceconfigs.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
