---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: releaseplanadmissions.appstudio.redhat.com
spec:
  group: appstudio.redhat.com
  names:
    kind: ReleasePlanAdmission
    listKind: ReleasePlanAdmissionList
    plural: releaseplanadmissions
    singular: releaseplanadmission
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: Display Name
      priority: 1
      type: string
    - jsonPath: .spec.application
      name: Application
      type: string
    - jsonPath: .spec.environment
      name: Environment
      type: string
    - jsonPath: .spec.releaseStrategy
      name: Strategy
      type: string
    - jsonPath: .spec.origin
      name: Origin
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ReleasePlanAdmission is the Schema for the ReleasePlanAdmissions
          API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ReleasePlanAdmissionSpec defines the desired state of ReleasePlanAdmission.
            properties:
              application:
                description: Application is a reference to the application to be released
                  in the managed namespace
                pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                type: string
              displayName:
                description: DisplayName is the long name of the ReleasePlanAdmission
                type: string
              environment:
                description: Environment defines which Environment will be used to
                  release the application
                pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                type: string
              extraData:
                description: ExtraData is used for providing extra data for the release
                  pipeline
                type: object
                x-kubernetes-preserve-unknown-fields: true
              origin:
                description: Origin references where the release requests should come
                  from
                pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                type: string
              releaseStrategy:
                description: ReleaseStrategy defines which strategy will be used to
                  release the application
                pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                type: string
            required:
            - application
            - origin
            - releaseStrategy
            type: object
          status:
            description: ReleasePlanAdmissionStatus defines the observed state of
              ReleasePlanAdmission.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
