---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: releaseserviceconfigs.appstudio.redhat.com
spec:
  group: appstudio.redhat.com
  names:
    kind: ReleaseServiceConfig
    listKind: ReleaseServiceConfigList
    plural: releaseserviceconfigs
    shortNames:
    - rsc
    singular: releaseserviceconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ReleaseServiceConfig is the Schema for the releaseserviceconfigs
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ReleaseServiceConfigSpec defines the desired state of ReleaseServiceConfig.
            properties:
              EmptyDirOverrides:
                description: VolumeOverrides is a map containing the volume type for
                  specific Pipeline git refs
                items:
                  description: EmptyDirOverrides defines the values usually set in
                    a PipelineRef using a git resolver.
                  properties:
                    pathInRepo:
                      description: PathInRepo is the path within the git repository
                        where the Pipeline definition can be found
                      type: string
                    revision:
                      description: Revision is the git revision where the Pipeline
                        definition can be found
                      type: string
                    url:
                      description: Url is the url to the git repo
                      type: string
                  required:
                  - pathInRepo
                  - revision
                  - url
                  type: object
                type: array
              debug:
                description: |-
                  Debug is the boolean that specifies whether or not the Release Service should run
                  in debug mode
                type: boolean
              defaultTimeouts:
                description: |-
                  DefaultTimeouts contain the default Tekton timeouts to be used in case they are
                  not specified in the ReleasePlanAdmission resource.
                properties:
                  finally:
                    description: Finally sets the maximum allowed duration of this
                      pipeline's finally
                    type: string
                  pipeline:
                    description: Pipeline sets the maximum allowed duration for execution
                      of the entire pipeline. The sum of individual timeouts for tasks
                      and finally must not exceed this value.
                    type: string
                  tasks:
                    description: Tasks sets the maximum allowed duration of this pipeline's
                      tasks
                    type: string
                type: object
              retryablePipelines:
                description: RetryablePipelines is a list of pipelines that are safe
                  to automatically retry on failure.
                items:
                  description: RetryablePipeline is a pipeline that is safe to automatically
                    retry on failure.
                  properties:
                    pathInRepo:
                      description: |-
                        PathInRepo is the path within the git repository where the Pipeline definition
                        can be found.
                      type: string
                    retryPolicy:
                      description: RetryPolicy defines how and when the pipeline is
                        retried after a failure.
                      properties:
                        disableOn:
                          description: DisableOn defines conditions that disable automatic
                            retries.
                          properties:
                            tags:
                              description: |-
                                Tags is a list of values which disable retries when present in the ReleasePlanAdmission
                                mapping data.
                              items:
                                type: string
                              type: array
                          type: object
                        maxRetries:
                          description: MaxRetries is the maximum number of retries
                            allowed for a pipeline.
                          minimum: 0
                          type: integer
                        mitigations:
                          description: Mitigations defines adjustment strategies to
                            apply on retry based on failure type
                          properties:
                            oomKill:
                              description: OOMKill defines adjustment for out-of-memory
                                failures
                              properties:
                                maxComputeResources:
                                  description: MaxComputeResources sets a upper limit
                                    on resources across retries.
                                  properties:
                                    claims:
                                      description: |-
                                        Claims lists the names of resources, defined in spec.resourceClaims,
                                        that are used by this container.

                                        This field depends on the
                                        DynamicResourceAllocation feature gate.

                                        This field is immutable. It can only be set for containers.
                                      items:
                                        description: ResourceClaim references one
                                          entry in PodSpec.ResourceClaims.
                                        properties:
                                          name:
                                            description: |-
                                              Name must match the name of one entry in pod.spec.resourceClaims of
                                              the Pod where this field is used. It makes that resource available
                                              inside a container.
                                            type: string
                                          request:
                                            description: |-
                                              Request is the name chosen for a request in the referenced claim.
                                              If empty, everything from the claim is made available, otherwise
                                              only the result of this request.
                                            type: string
                                        required:
                                        - name
                                        type: object
                                      type: array
                                      x-kubernetes-list-map-keys:
                                      - name
                                      x-kubernetes-list-type: map
                                    limits:
                                      additionalProperties:
                                        anyOf:
                                        - type: integer
                                        - type: string
                                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                        x-kubernetes-int-or-string: true
                                      description: |-
                                        Limits describes the maximum amount of compute resources allowed.
                                        More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                                      type: object
                                    requests:
                                      additionalProperties:
                                        anyOf:
                                        - type: integer
                                        - type: string
                                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                        x-kubernetes-int-or-string: true
                                      description: |-
                                        Requests describes the minimum amount of compute resources required.
                                        If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
                                        otherwise to an implementation-defined value. Requests cannot exceed Limits.
                                        More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                                      type: object
                                  type: object
                                multiplier:
                                  description: Multiplier is a factor used to multiply
                                    memory limits on each retry
                                  pattern: ^[0-9]+(\.[0-9]+)?$
                                  type: string
                              required:
                              - multiplier
                              type: object
                            timeout:
                              description: Timeout defines adjustment for timeout
                                failures.
                              properties:
                                increment:
                                  description: Increment is the duration to add to
                                    the timeout on each retry.
                                  type: string
                                maxTimeout:
                                  description: MaxTimeout is the maximum time allowed
                                    across retries.
                                  type: string
                              required:
                              - increment
                              type: object
                          type: object
                      required:
                      - maxRetries
                      type: object
                    revision:
                      description: Revision is the git revision where the Pipeline
                        definition can be found.
                      type: string
                    url:
                      description: Url is the url to the git repo.
                      type: string
                  required:
                  - pathInRepo
                  - retryPolicy
                  - revision
                  - url
                  type: object
                type: array
            type: object
          status:
            description: ReleaseServiceConfigStatus defines the observed state of
              ReleaseServiceConfig.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
